### ISSUE TITLE
Sparse Checkout

### ISSUE THREAD

**Issue by chrodriguezs** [Febiunz/AzureDevOpsExtensionGitClone#10]
Hi,
I would like to clone/checkout only a part (a subdirectory) of the repository with the Azure Devops Extension Git Clone, like it's done with the "sparse-checkout" command.

https://stackoverflow.com/questions/56442203/checkout-part-of-a-branch-in-azure-devops-pipelines-getsources
https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/pipelines/templates/steps/sparse-checkout.yml
https://git-scm.com/docs/git-sparse-checkout
https://codingwithtaz.blog/2021/11/22/monorepos-with-azure-pipelines/
https://www.appsloveworld.com/azure-pipelines/1/checkout-part-of-a-branch-in-azure-devops-pipelines-getsources

Is it possible with the Azure Devops Extension Git Clone please?
Thanks

**Comment by Febiunz** [comment]
Hi, no that is unfortunately not possible right now. But with the given articles you should be able to get this working with a script task I think? And you are more then welcome to contribute and create a pull request with the needed changes. Should not be to hard to be able to add the sparse as an optional parameter I am thinking. Are you willing to contribute with a PR that I can review? Thank you in advance.
