### ISSUE TITLE
Git Repository Clone task fails when trying to update a variable

### ISSUE THREAD

**Issue by JohnH-Work** [Febiunz/AzureDevOpsExtensionGitClone#5]
After the latest updates, the task always fails with:
##[error]Unable to process command '##vso[task.setvariable variable=;isOutput=true;]C:\BuildScripts' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
##[error]Required field 'variable' is missing in ##vso[task.setvariable] command.

It appears that the variable that should be passed in ($RepositoryName) doesn't actually exist for us, so the variable name ends up being empty.

**Comment by Febiunz** [comment]
That is really strange. Which repository URL do you use to fill the Repository URL parameter of the task? Are you using a non TFS or Azure DevOps git repository here maybe?

**Comment by yfrindel** [comment]
in my opinion this syntax is not correct (2 "$") : 
![image](https://user-images.githubusercontent.com/22955005/83534167-ce642f80-a4f0-11ea-8ca2-9bc06a3c7505.png)

**Comment by JohnH-Work** [comment]
The problem is that it only populates $RepositoryName if $RepositoryPath is not specified, but it always needs it for the variable update at the end.

**Comment by Febiunz** [comment]
What did you use for the Repository Path parameter then?

**Comment by JohnH-Work** [comment]
We've got Repository Path set to: C:\BuildScripts
Repository URL set to: https://dev.azure.com/redacted/Shared/_git/BuildScripts

**Comment by Febiunz** [comment]
> in my opinion this syntax is not correct (2 "$") :
> ![image](https://user-images.githubusercontent.com/22955005/83534167-ce642f80-a4f0-11ea-8ca2-9bc06a3c7505.png)

There is nothing wrong with the syntax, it works as expected. Problems is indeed in the not always filling the repository name variable, which is needed.

**Comment by Febiunz** [comment]
> We've got Repository Path set to: C:\BuildScripts
> Repository URL set to: https://dev.azure.com/redacted/Shared/_git/BuildScripts

Clear issue! I will have a look at this and report back as quick as possible.

**Comment by Febiunz** [comment]
I just released a new version. I tested it, and I think it works. Could you guys check please?

**Comment by JohnH-Work** [comment]
Yes, that's working for us. Thanks!

**Comment by Febiunz** [comment]
Nice! Thanks for the feedback! Enjoy using the extension. If not to much to ask, could you write a review on the extension? Thanks in advance!
