### ISSUE TITLE
Clone only a part of a repository

### ISSUE THREAD

**Issue by yfrindel** [Febiunz/AzureDevOpsExtensionGitClone#7]
Hi,
I would like to clone/checkout only a part (a subdirectory) of the repository with the Azure Devops Extension Git Clone, like it's done with the "sparse-checkout" command.
https://stackoverflow.com/questions/56442203/checkout-part-of-a-branch-in-azure-devops-pipelines-getsources/56442503
Is it possible with the Azure Devops Extension Git Clone please? And How?
Thanks

**Comment by Febiunz** [comment]
Hi, as of this moment that is not possible with this extension unfortunately. Please feel free to contribute to this repo and add this functionality with a PR. In this way I can review it, and integrate it in the extension.

Kind regards, Fabian
