### ISSUE TITLE
Doesn't work on linux agents - option to use powershell core?

### ISSUE THREAD

**Issue by dazinator** [Febiunz/AzureDevOpsExtensionGitClone#8]
When attempting to run this task on a linux build agent devops states the task requires powershell and is designed to run on windows agents only.

Perhaps an option could be added to use powershell core? Which would enable this task to also run on linux agents?

**Comment by Febiunz** [comment]
Sure, maybe that is an option. You're more then welcome to submit a PR with changes :)
